### ISSUE TITLE
skidl unable to open KiCAD symbol library

### ISSUE THREAD

**Issue by Timot05** [devbisme/skidl#154]
I'm trying to run the example code provided in the introduction: [here](https://devbisme.github.io/skidl/#introduction).

I get the following error:

```
WARNING: Could not load KiCad schematic library "device", falling back to backup library. @ [/Users/me/Dev/folder/example.py:14]
Traceback (most recent call last):
  File "/Users/me/Dev/folder/example.py", line 14, in <module>
    r1, r2 = 2 * Part ('device', 'R', TEMPLATE) # Create two resistors.
  File "/opt/homebrew/lib/python3.9/site-packages/skidl/part.py", line 189, in __init__
    raise e
  File "/opt/homebrew/lib/python3.9/site-packages/skidl/part.py", line 179, in __init__
    lib = SchLib(filename=libname, tool=tool)
  File "/opt/homebrew/lib/python3.9/site-packages/skidl/schlib.py", line 84, in __init__
    load_func(
  File "/opt/homebrew/lib/python3.9/site-packages/skidl/tools/kicad/kicad.py", line 67, in load_sch_lib
    raise FileNotFoundError(
FileNotFoundError: Unable to open KiCad Schematic Library File device
```

I installed KiCAD6 and installed the latest version of skidl on macOS.

I set my environment variable like so:
`export KICAD_SYMBOL_DIR="/Applications/KiCad/KiCad.app/Contents/SharedSupport/symbols/"`

Thanks for the support!

**Comment by Timot05** [comment]
Make sure you have "device" in your library. In my case, it wasn't there. Fixed now!
