### ISSUE TITLE
the function generate_pcb() can't generate PCB file

### ISSUE THREAD

**Issue by wofy-92** [devbisme/skidl#191]
**Describe the bug**
Hi devbisme, When I running the function generate_pcb(), I get a WARNING:
`WARNING: kinet2pcb module is missing. Can't generate a KiCad PCB without it.`
but I have installed kinet2pcb 

** The test code in the JupyterLab**
```python
from skidl import *

esp32 = Part('RF_Module','ESP32-WROOM-32', footprint='RF_Module:ESP32-WROOM-32')
generate_pcb()
```
** output message**
`  WARNING: kinet2pcb module is missing. Can't generate a KiCad PCB without it. @ [D:\Python310\Lib\site-packages\IPython\core\interactiveshell.py:3433=>C:\Users\Administrator\AppData\Local\Temp\ipykernel_29400\1868553726.py:4]
INFO: 1 warnings found while creating PCB.
INFO: 0 errors found while creating PCB. `

**Screenshots**

![image](https://github.com/devbisme/skidl/assets/20929787/cfeaaeb6-4a07-4d95-b107-9eabc2d73282)

![image](https://github.com/devbisme/skidl/assets/20929787/662bb100-3a9e-4e84-8d06-af7ca517de43)

**Desktop (please complete the following information):**
 - Windows11
 - Python3.10.0
 - SKiDL1.2.1
 - kinet2pcb1.1.0

**Comment by alihsepahvand** [comment]
did you fix this?

**Comment by roboPanda69** [comment]
Hi @devbisme if this problem is not taken, could I solve this ?

**Comment by devbisme** [comment]
I'm not seeing this error when running the tests on linux. You can try it on Windows and see if the error occurs there. If so, then go ahead and attempt a fix. Please use the `version1` branch to make your fix. I added a test for `generate_pcb()` to `test_generate.py`, so make sure to fetch your branch to get that change.

If you don't see any errors, then I can close this issue.

**Comment by roboPanda69** [comment]
Hi Dave, the problem was majorly for Windows user. We have to include the pcbnew module in our Python library search path in the code of kinet2pcb.py.

I am writing instructions on how one could change the same for beginners using the code for the first time - 
1. Open kinet2pcb.py file (inside kinet2pcb folder), in line 15  we have `sys.path.append('/usr/lib/python3/dist-packages')` , here we have to change this path so that it could locate pcbnew.py file.
2. For KiCAD 8.0 the default path is "C:/Program Files/KiCad/8.0/bin/Lib/site-packages", so in the code we have to change line 15 of kicad.py to ` sys.path.append("C:\\Program Files\\KiCad\\8.0\\bin\\Lib\\site-packages") `
3. After this some might face an error for ` ImportError: DLL load failed while importing _pcbnew: The specified module could not be found. `
4. To solve the above problem we have to Copy _pcbnew.pyd from the sites-packages folder to the KiCad/bin folder. [ For reference - https://forum.kicad.info/t/cannot-import-pcbnew-when-running-kicad-bin-python-exe-on-the-command-line/14519/15?u=prashun_pandey ]
5. We have to add `sys.path.append("C:\\Program Files\\KiCad\\8.0\\bin\\")` at line 14. And then our program would work perfectly.

Here is how code looked before - 
```
from past.builtins import basestring
import argparse
import logging
import os
import os.path
import re
import shutil
import sys

import kinparse

sys.path.append('/usr/lib/python3/dist-packages')
import pcbnew
import hierplace
```

For Windows user they have to change as - 
```
from past.builtins import basestring
import argparse
import logging
import os
import os.path
import re
import shutil
import sys
import platform

import kinparse

sys.path.append("C:\\Program Files\\KiCad\\8.0\\bin\\")
sys.path.append("C:\\Program Files\\KiCad\\8.0\\bin\\Lib\\site-packages")

import pcbnew
import hierplace
```

**Comment by devbisme** [comment]
Thanks for looking at this, @roboPanda69. It appears that the changes need to be made to the `kinet2pcb` utility, so I'll do that over there. Then I'll come back and close this issue.

**Comment by 14790897** [comment]
Thanks for the quick update! I’ve tested v1.1.3 and found two issues:

1. Critical Bug (TypeError) in Path Joining:

Your path logic on Windows is still using a tuple inside os.path.join(), causing an immediate TypeError.

Please check the code around line 18-20 in kinet2pcb.py:

Incorrect (Type Error): os.path.join(("C:\\Program Files\\KiCad", version))
            sys.path.extend(((os.path.join(ki_pth, "bin"), os.path.join(ki_pth, "bin", "Lib", "site-packages"))))

Correct (Fix): os.path.join("C:\\Program Files\\KiCad", version)             
sys.path.extend((os.path.join(ki_pth, "bin"), os.path.join(ki_pth, "bin", "Lib", "site-packages")))

2. KiCad API Failure 

After fixing the path, the script hits an AttributeError: 'NoneType' object has no attribute 'FootprintLoad'.
```
Traceback (most recent call last):
  File "C:\git-program\Embedded\beautiful-eyes\eyes-kicad\airm2m.py", line 422, in <module>
    generate_pcb()
  File "C:\Users\13963\OneDrive\文档\KiCad\9.0\3rdparty\Python311\site-packages\skidl\circuit.py", line 847, in generate_pcb
    tool_modules[tool].gen_pcb(self, file_, fp_libs=fp_libs)
  File "C:\Users\13963\OneDrive\文档\KiCad\9.0\3rdparty\Python311\site-packages\skidl\tools\kicad9\gen_pcb.py", line 39, in gen_pcb
    kinet2pcb.kinet2pcb(circuit, pcb_file, fp_libs)
  File "C:\Users\13963\OneDrive\文档\KiCad\9.0\3rdparty\Python311\site-packages\kinet2pcb\kinet2pcb.py", line 315, in kinet2pcb
    fp = pcbnew.FootprintLoad(lib_uri, fp_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\KiCad\9.0\bin\Lib\site-packages\pcbnew.py", line 21635, in FootprintLoad
    return plug.FootprintLoad(libname,name,preserveUUID)
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'FootprintLoad'
```
I also  encounter this bug
<img width="962" height="376" alt="Image" src="https://github.com/user-attachments/assets/4cdc4ac6-c295-4ee5-a139-42ec89857641" />

**Comment by devbisme** [comment]
Thanks for the error reports. (I tested under linux so I didn't find these Windows-related errors).

I fixed the first error in the `master` branch of `kinet2pcb`.

I'm not sure why the second error is occuring unless the import of the `pcbnew` package is finding something that's not actually the intended package. I placed an exception if the loop that searches for the import directory doesn't find anything, but I doubt this is the cause of the error.

I have no idea about the ACTIONS_PLUGINS error since `kinet2pcb` isn't a KiCad plugin.

Install from the `master` branch of `kinet2pcb` and let me know what new errors we find. Thanks!
