### ISSUE TITLE
 SKiDL 1.2.2 fails trivial test for KiCAD 8 

### ISSUE THREAD

**Issue by 32bitmicro** [devbisme/skidl#219]
**Describe the bug**

SKiDL 1.2.2 fails trivial test for KiCAD 8 on Ubuntu 22.04 with Python 3.11.5 :

```
from skidl import *
set_default_tool(KICAD8)

generate_schematic()
generate_netlist()
```

**To Reproduce**
1. Save code as test_kicad8.py
2. export KICAD8_SYMBOL_DIR=/usr/share/kicad/symbols/
3. Run it with: `python test_kicad8.py`

**Expected behavior**
A clean run with no exceptions.

**Screenshots**
```
pawel:~/skidlboardtest$ export KICAD8_SYMBOL_DIR=/usr/share/kicad/symbols/
pawel:~/skidlboardtest$ python test_kicad8.py 
WARNING: KICAD7_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [/home/pawel/skidlboardtest/<frozen importlib._bootstrap_external>:940=>/home/pawel/skidlboardtest/<frozen importlib._bootstrap>:241]
WARNING: KICAD6_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [/home/pawel/skidlboardtest/<frozen importlib._bootstrap_external>:940=>/home/pawel/skidlboardtest/<frozen importlib._bootstrap>:241]
WARNING: KICAD_SYMBOL_DIR environment variable is missing, so the default KiCad symbol libraries won't be searched. @ [/home/pawel/skidlboardtest/<frozen importlib._bootstrap_external>:940=>/home/pawel/skidlboardtest/<frozen importlib._bootstrap>:241]
Traceback (most recent call last):
  File "/home/pawel/skidlboardtest/test_kicad8.py", line 4, in <module>
    generate_schematic()
  File "/home/pawel/skidlboardtest/3rdparty/skidl/src/skidl/circuit.py", line 1073, in generate_schematic
    tool_modules[tool].gen_schematic(self, **kwargs)
  File "/home/pawel/skidlboardtest/3rdparty/skidl/src/skidl/tools/kicad8/gen_schematic.py", line 739, in gen_schematic
    node.place(expansion_factor=expansion_factor, **options)
  File "/home/pawel/skidlboardtest/3rdparty/skidl/src/skidl/schematics/place.py", line 1516, in place
    node.calc_bbox()
  File "/home/pawel/skidlboardtest/3rdparty/skidl/src/skidl/schematics/node.py", line 229, in calc_bbox
    self.bbox = self.external_bbox()
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/pawel/skidlboardtest/3rdparty/skidl/src/skidl/schematics/node.py", line 200, in external_bbox
    bbox.add(Point(len("File: " + self.sheet_filename) * self.filename_sz, 0))
                       ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
```

**Desktop (please complete the following information):**
 - Application: KiCad x86_64 on x86_64 Version: 8.0.3-8.0.3-0~ubuntu22.04.1, release build
 - SKiDL version 1.2.2

**Comment by devbisme** [comment]
Thanks for reporting this!

SKiDL only generates schematics for KiCad version 5. There is no support for versions 6, 7, or 8. That said, SKiDL should raise a "not implemented" exception when this is attempted. I'll modify the code to do that.

**Comment by LoQiseaking69** [comment]
I have KiCad 6... skidl seems to have a lot of gaps... I can't get environment variables to be recognized even if I hardcode the paths...

**Comment by LoQiseaking69** [comment]
@devbisme thanks! I was having the same issue in 6 but just read your comment.
